version: '3.1'

services:
  client:
    image: bennythink/searchgram:ng
    env_file:
      - env/gram.env
    restart: always
    depends_on:
      - meili
    volumes:
      - ./sg_data/session:/SearchGram/searchgram/session
    command:
      - client.py

  bot:
    image: bennythink/searchgram:ng
    env_file:
      - env/gram.env
    restart: always
    depends_on:
      - meili
    volumes:
      - ./sg_data/session:/SearchGram/searchgram/session
    command:
      - bot.py

  meili:
    image: getmeili/meilisearch:v1.1.0-rc.3
    restart: always
    volumes:
      - ./sg_data/:/meili_data
    env_file:
      - env/gram.env
    ports:
      - "127.0.0.1:7700:7700"
